# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  # Triggered on push by .github/workflows/release.yaml
  workflow_call:

jobs:
  lint-workflows:
    name: Lint .github/workflows/
    uses: canonical/data-platform-workflows/.github/workflows/lint_workflows.yaml@v53.0.0
    permissions:
      contents: read
    cache-mode: none

  test:
    strategy:
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    name: Test rock | ${{ matrix.runner }}
    needs:
      - lint-workflows
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up environment
        run: |
          sudo snap install lxd
          sudo adduser "$USER" lxd
          # `newgrp` does not work in GitHub Actions; use `sudo --user` instead
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd waitready
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd init --auto
          # Workaround for Docker & LXD on same machine
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT

          sudo snap install rockcraft --classic
      - name: rockcraft test
        run: sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- rockcraft test -v
    permissions: {}
    cache-mode: none
