# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Rock Build/Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  # Triggered on push by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_rock.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}

jobs:
  lint-workflows:
    name: Lint .github/workflows/
    uses: canonical/data-platform-workflows/.github/workflows/lint_workflows.yaml@v53.0.0
    permissions:
      contents: read
    cache-mode: none

  build:
    name: Build rock
    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@v53.0.0
    permissions:
      contents: read
    cache-mode: none

  test:
    name: Test rock | ${{ matrix.runner }}
    timeout-minutes: 10
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
    needs:
      - lint-workflows
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Run tests
        run: |
          # lxd is necessary for spread
          sudo snap install lxd
          sudo adduser "$USER" lxd
          # `newgrp` does not work in GitHub Actions; use `sudo --user` instead
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd waitready
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- lxd init --auto
          # Workaround for Docker & LXD on same machine
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT

          sudo snap install rockcraft --classic
          sudo --user "$USER" --preserve-env --preserve-env=PATH -- env -- rockcraft test
    permissions: {}
    cache-mode: none
