# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to OCI Factory

on:
  push:
    branches:
      - '18'
  workflow_dispatch:

jobs:
  ci-tests:
    name: Tests
    uses: $/.github/workflows/ci.yaml
    permissions:
      contents: read
    cache-mode: none

  release:
    name: Release rock to OCI Factory
    needs:
      - ci-tests
    runs-on: ubuntu-latest
    environment:
      name: edge
      deployment: true
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Set up environment
        run: |
          sudo apt install golang-go -y
          go install github.com/canonical/oci-factory/tools/cli-client/cmd/oci-factory@latest
      - name: Trigger build & release to edge
        run: ~/go/bin/oci-factory upload -y --release track=18-26.04,risks=edge,eol=2031-04-23
        env:
          GITHUB_TOKEN: ${{ secrets.DP_BOT_PAT_OCI_FACTORY }}
    permissions: {}
    cache-mode: none
